name: platform_view_swift
environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
