name: jsonexample
description: A demonstration of JSON parsing

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0
  built_collection: ^4.2.2
  built_value: ^6.7.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  built_value_generator: ^6.7.1
  json_serializable: ^3.2.2
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
