name: jsonexample
description: A demonstration of JSON parsing
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0
  built_collection: ^5.0.0
  built_value: ^8.0.0

  flutter:
    sdk: flutter

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  built_value_generator: ^8.0.0
  json_serializable: ^4.0.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
