name: jsonexample
description: A demonstration of JSON parsing

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  json_annotation: ^1.0.0
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^6.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: '>=0.9.0 <0.11.0'
  built_value_generator: ^6.1.0
  json_serializable: ^1.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

