name: flutter_maps_firestore
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.4
  google_maps_flutter: ^1.0.6
  google_maps_webservice: ^0.0.18
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
