name: flutter_maps_firestore
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  google_maps_flutter: ^1.2.0
  google_maps_webservice: ^0.0.19
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
